No scaling
alexgurr/vivus pull request #1
Opened 2021-04-12 22:23 UTC by maxwellito

Hey @alexgurr

It took me a bit longer than expected but when you have moment I would like to get your views on this PR.
Feel free to suggest better warnings, method names and docs.

2021-04-14 01:26 UTC, alexgurr requested changes

2021-04-14 01:26 UTC, alexgurr commented on dist/vivus.js
> +Vivus.prototype.recalcThrottle = function () {
This isn't actually a throttle or doing any throttling. It's also technically not private because it's on the prototype?

```suggestion
Vivus.prototype.performLineRecalc = function () {
```

2021-04-14 01:26 UTC, alexgurr commented on dist/vivus.js
> +    this.recalcThrottle();
```suggestion
    this.performLineRecalc();
```

2021-04-14 01:26 UTC, alexgurr commented on readme.md
> +  },
```suggestion
  }
```

2021-04-14 01:26 UTC, alexgurr commented on readme.md
> +    animTimingFunction: Vivus.EASE,
```suggestion
    animTimingFunction: Vivus.EASE
```

2021-04-14 01:26 UTC, alexgurr commented on readme.md
> +Some SVG elements might use non sclaling properties, like `vector-effect="non-scaling-stroke"`, and are more likely to cause glitches. To give a bit of context, at init time, Vivus will map all the e
```suggestion
Some SVG elements might use non scaling properties such as `vector-effect="non-scaling-stroke"`, which requires some additional custom logic. On instance construction Vivus will map all the child elements in the SVG and calculate their line length. If the element is resized during the animation, the calculated stroke style properties become invalid and the SVG will display incorrectly.
```

2021-04-14 01:26 UTC, alexgurr commented on readme.md
> +To keep animation consistency, the method `.recalc()` must be called when the SVG is resized. It will re-calculate the line length on affected elements at the next frame calculation. The following sn
```suggestion
To keep animation consistency, the method `recalc` should be called when the SVG is resized. It will re-calculate the line length on affected child elements on the next frame calculation.

Code example:
```

2021-04-14 01:26 UTC, alexgurr commented on readme.md
> +// Create your Vivus object
```suggestion
// Create your Vivus instance
```

2021-04-14 01:26 UTC, alexgurr commented on readme.md
> +// Start your observer to update the SVG on resize
```suggestion
// Create your observer and set up a callback on resize
```

2021-04-14 01:26 UTC, alexgurr commented on readme.md
> +resizeObserver.observe(vivusObject.el);
```suggestion

resizeObserver.observe(vivusObject.el);
```

2021-04-14 01:26 UTC, alexgurr commented on readme.md
> +  vivusObject.recalc();
```suggestion
  // Recalculate the line lengths
  vivusObject.recalc();
```

2021-04-14 01:26 UTC, alexgurr commented on readme.md
> +If you're not sure if your SVG is affected, Vivus will provide a warning in the console to give a bit of context.
```suggestion
Vivus will provide a warning in the console when it detects stroke scaling.
```

2021-04-14 01:26 UTC, alexgurr commented on src/vivus.js
> +Vivus.prototype.recalcThrottle = function () {
Same changes as above, including name + comment improvements

2021-04-14 01:26 UTC, alexgurr commented on src/vivus.js
> +  if (hasNonScale) {
Same changes as above

2021-04-14 01:27 UTC, alexgurr commented
Left some comments. Let me know how it goes :)

2021-04-14 22:49 UTC, maxwellito commented
Thanks for your review. Everything made sense. The reason I used 'throttle' in one of the method name is because if the method is called multiple times between 2 frames (likely to happen during resize), the processing would be applied only once. 

Also sorry about including the dist files, terrible mistake. I applied your comments on the source file. 

I really enjoy the "Add suggestion" feature :)

2021-04-15 03:33 UTC, alexgurr commented
The dist files are in the main repository too. I would actually recommend as part of this PR removing that entire directory and adding it to gitignore?

2021-04-15 18:58 UTC, maxwellito commented
Hey Alex, thanks for the suggestion but I would advise to revert your last commit. I know it's not great to have the dist folder in the repository, however a lot of other things depends on it. I know some CDN uses it and it's also necessary for the demo page (ok that could be changed). I think it would need more time to remove the dist folder. Sorry about that

2021-04-15 23:53 UTC, alexgurr commented
Ok. Have you addressed the PR feedback in src and done a rebuild, so the changes are in both?

2021-04-16 21:35 UTC, maxwellito commented
Yes the changes should be in both now. Also, I will have to bump the version, build, and publish once on master :)

2021-04-16 23:55 UTC, alexgurr approved these changes

2021-04-16 23:55 UTC, merged